### ISSUE TITLE
index page

### ISSUE THREAD

**Issue by skayikci** [suathh/MovieProject#3]
Please create an index page. And when you decide to create one, please put here the things you will put on the page.

**Comment by suathh** [comment]
I will create an index page at end of project now I am working on functionalities of other pages

**Comment by skayikci** [comment]
it can go parallel. this way we can see the changes directly looking at the main page, otherwise we are forced to see changes by curl or sth.

**Comment by suathh** [comment]
okey , I will go for it

**Comment by suathh** [comment]
issue'u çözen commit id 6f90e0b1f8fef7d2c6a03046eaeb51ddef84cee9
